{
 "bad": false,
 "pre_pr_migrator_attempts": {
  "numpy2": 147,
  "openmpi5": 175,
  "python312": 67
 },
 "pre_pr_migrator_status": {
  "numpy2": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/10414013608\">bot CI job</a>): main:\nError running rerender-feedstock in container - error RuntimeError raised:\n'Failed to rerender.\noutput: Adding in variants from internal_defaults\nAdding in variants from /tmp/tmp9_8sn8r7/conda-smithy/conda_build_config.yaml\nAdding in variants from /tmp/tmp1p8tp7hv/fluidfft-fftwmpi-feedstock/recipe/conda_build_config.yaml\nAdding in variants from argument_variants\nINFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2024.08.16.02.02.38\nINFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmp9_8sn8r7/conda-smithy\nINFO:conda_smithy.configure_feedstock:__pycache__ rendering is skipped\nINFO:conda_smithy.configure_feedstock:README rendering is skipped\nINFO:conda_smithy.configure_feedstock:numpy2.yaml from feedstock is ignored and upstream version is used\nWARNING: Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.\nWARNING: Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.\nWARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.23\nINFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmp9_8sn8r7/conda-smithy/share/conda-forge/migrations/numpy2.yaml\nINFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmp9_8sn8r7/conda-smithy/share/conda-forge/migrations/numpy2.yaml\nINFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmp9_8sn8r7/conda-smithy/share/conda-forge/migrations/numpy2.yaml\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py\", line 2010, in _get_contents\n    rendered = template.render(environment=env)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/jinja2/environment.py\", line 1304, in render\n    self.environment.handle_exception()\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/jinja2/environment.py\", line 939, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/tmp/tmp1p8tp7hv/fluidfft-fftwmpi-feedstock/recipe/meta.yaml\", line 3, in top-level template code\n    {% set mpi = mpi or 'mpich' %}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\njinja2.exceptions.UndefinedError: 'mpi' is undefined\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 758, in main\n    args.subcommand_func(args)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 601, in __call__\n    self._call(args, args.temporary_directory)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 604, in _call\n    configure_feedstock.main(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2780, in main\n    render_azure(env, config, forge_dir, return_metadata=True)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 1866, in render_azure\n    return _render_ci_provider(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 1085, in _render_ci_provider\n    metas = _conda_build_api_render_for_smithy(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 885, in _conda_build_api_render_for_smithy\n    metadata_tuples = render_recipe(\n                      ^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/render.py\", line 994, in render_recipe\n    return distribute_variants(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/render.py\", line 883, in distribute_variants\n    mv.parse_until_resolved(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py\", line 1364, in parse_until_resolved\n    self.parse_again(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py\", line 1273, in parse_again\n    self._get_contents(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py\", line 2020, in _get_contents\n    raise CondaBuildUserError(\nconda_build.exceptions.CondaBuildUserError: Failed to render jinja template in /tmp/tmp1p8tp7hv/fluidfft-fftwmpi-feedstock/recipe/meta.yaml:\n'mpi' is undefined\n\n'",
  "openmpi5": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/10415062205\">bot CI job</a>): main:\nError running rerender-feedstock in container - error RuntimeError raised:\n'Failed to rerender.\noutput: Adding in variants from internal_defaults\nAdding in variants from /tmp/tmpj3128u9d/conda-smithy/conda_build_config.yaml\nAdding in variants from /tmp/tmpq9vcr0ib/fluidfft-fftwmpi-feedstock/recipe/conda_build_config.yaml\nAdding in variants from argument_variants\nINFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2024.08.16.02.02.38\nINFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmpj3128u9d/conda-smithy\nINFO:conda_smithy.configure_feedstock:__pycache__ rendering is skipped\nINFO:conda_smithy.configure_feedstock:README rendering is skipped\nINFO:conda_smithy.configure_feedstock:openmpi5.yaml from feedstock is ignored and upstream version is used\nWARNING: Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.\nWARNING: Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.\nWARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.23\nINFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmpj3128u9d/conda-smithy/share/conda-forge/migrations/openmpi5.yaml\nINFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmpj3128u9d/conda-smithy/share/conda-forge/migrations/openmpi5.yaml\nINFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmpj3128u9d/conda-smithy/share/conda-forge/migrations/openmpi5.yaml\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py\", line 2010, in _get_contents\n    rendered = template.render(environment=env)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/jinja2/environment.py\", line 1304, in render\n    self.environment.handle_exception()\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/jinja2/environment.py\", line 939, in handle_exception\n    raise rewrite_traceback_stack(source=source)\n  File \"/tmp/tmpq9vcr0ib/fluidfft-fftwmpi-feedstock/recipe/meta.yaml\", line 3, in top-level template code\n    {% set mpi = mpi or 'mpich' %}\n    ^^^^^^^^^^^^^^^^^^^^^^^^^\njinja2.exceptions.UndefinedError: 'mpi' is undefined\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 758, in main\n    args.subcommand_func(args)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 601, in __call__\n    self._call(args, args.temporary_directory)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 604, in _call\n    configure_feedstock.main(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2780, in main\n    render_azure(env, config, forge_dir, return_metadata=True)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 1866, in render_azure\n    return _render_ci_provider(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 1085, in _render_ci_provider\n    metas = _conda_build_api_render_for_smithy(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 885, in _conda_build_api_render_for_smithy\n    metadata_tuples = render_recipe(\n                      ^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/render.py\", line 994, in render_recipe\n    return distribute_variants(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/render.py\", line 883, in distribute_variants\n    mv.parse_until_resolved(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py\", line 1364, in parse_until_resolved\n    self.parse_again(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py\", line 1273, in parse_again\n    self._get_contents(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_build/metadata.py\", line 2020, in _get_contents\n    raise CondaBuildUserError(\nconda_build.exceptions.CondaBuildUserError: Failed to render jinja template in /tmp/tmpq9vcr0ib/fluidfft-fftwmpi-feedstock/recipe/meta.yaml:\n'mpi' is undefined\n\n'"
 }
}