{
 "PRed": [
  {
   "PR": {
    "number": 1,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "r-base42"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": 7,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "r_base43"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad": false,
 "pinning_version": "2023.06.19.09.23.46",
 "pre_pr_migrator_attempts": {
  "r-base44_and_m2w64-ucrt": 92
 },
 "pre_pr_migrator_status": {
  "r-base44_and_m2w64-ucrt": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/10427934937\">bot CI job</a>): main:\nError running rerender-feedstock in container - error RuntimeError raised:\n'Failed to rerender.\noutput: Traceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 758, in main\n    args.subcommand_func(args)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 601, in __call__\n    self._call(args, args.temporary_directory)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 604, in _call\n    configure_feedstock.main(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2740, in main\n    exclusive_config_file, cf_pinning_ver = get_cached_cfp_file_path(\n                                            ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2553, in get_cached_cfp_file_path\n    current_pinning_version = get_most_recent_version(\n                              ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2426, in get_most_recent_version\n    request.raise_for_status()\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 524 Server Error:  for url: https://api.anaconda.org/package/conda-forge/conda-forge-pinning\n\n'"
 },
 "smithy_version": "3.23.1"
}