{
 "bad": false,
 "new_version": "0.4.2",
 "new_version_attempts": {
  "0.4.0": 1,
  "0.4.2": 99
 },
 "new_version_errors": {
  "0.4.2": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/10437554960\">bot CI job</a>): main:\nError running migrate-feedstock in container - error VersionMigrationError raised:\n'The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!\n\nPlease check the URLs in your recipe with version '0.4.2' to make sure they exist!\n\nWe also found the following errors:\n\n - We found a problem parsing the recipe for version '0.4.2': \n\nDuplicateKeyError('while constructing a mapping',   in \"<unicode string>\", line 4, column 1:\n    package:\n    ^ (line: 4), 'found duplicate key \"test\" with value \"{\\'imports\\': [\\'jupyter_contrib_core\\'], \\'commands\\': [\\'pip check\\', \\'jupyter-contrib --help\\'], \\'requires\\': [\\'pip\\']}\" (original value: \"{\\'imports\\': [\\'jupyter_contrib_core\\', \\'jupyter_contrib_core.application\\', \\'jupyter_contrib_core.notebook_compat\\', \\'jupyter_contrib_core.notebook_compat.nbextensions\\', \\'jupyter_contrib_core.notebook_compat.serverextensions\\', \\'jupyter_contrib_core.notebook_compat._compat\\', \\'jupyter_contrib_core.notebook_compat._compat.nbextensions\\', \\'jupyter_contrib_core.notebook_compat._compat.serverextensions\\']}\")',   in \"<unicode string>\", line 43, column 1:\n    test:\n    ^ (line: 43), '\\n                    To suppress this check see:\\n                        http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys\\n                    ', '                    Duplicate keys will become an error in future releases, and are errors\\n                    by default when using the new API.\\n                    ')\n\ntraceback:\n  File \"/opt/autotick-bot/conda_forge_tick/update_recipe/version.py\", line 415, in update_version\n    cmeta = CondaMetaYAML(raw_meta_yaml)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/recipe_parser/_parser.py\", line 525, in __init__\n    self.meta = self._parser.load(\"\".join(lines))\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/main.py\", line 451, in load\n    return constructor.get_single_data()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 116, in get_single_data\n    return self.construct_document(node)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 125, in construct_document\n    for _dummy in generator:\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1476, in construct_yaml_map\n    self.construct_mapping(node, data, deep=True)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 1366, in construct_mapping\n    if self.check_mapping_key(node, key_node, maptyp, key, value):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/ruamel/yaml/constructor.py\", line 278, in check_mapping_key\n    raise DuplicateKeyError(*args)\n\n'"
 }
}