{
 "PRed": [
  {
   "PR": {
    "number": 1,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "CompilerRebuild",
    "migrator_version": 1,
    "name": "Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 3,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "GFortranOSXRebuild",
    "migrator_version": 0,
    "name": "fortran_compiler_stub-7"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 4,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python38"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 5,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MatplotlibBase",
    "migrator_version": 0,
    "name": "matplotlib-to-matplotlib-base"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 8,
    "state": "closed"
   },
   "data": {
    "bot_rerun": 1584000686.1944163,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "1.0.2"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 10,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "pypy"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 11,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 2,
    "migrator_version": 0,
    "name": "python39"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 12,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "gcc930"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 13,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "pypy37"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 14,
    "state": "closed"
   },
   "data": {
    "bot_rerun": 1630404776.5378406,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "pypy37-windows"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 15,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "pypy37-windows"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 16,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python310"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  }
 ],
 "bad": {
  "exception": "Error running rerender-feedstock in container - error RuntimeError raised:\n'Failed to rerender.\noutput: Adding in variants from internal_defaults\nAdding in variants from /tmp/tmpgk3wptuu/conda-smithy/conda_build_config.yaml\nINFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2024.08.18.18.50.57\nINFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmpgk3wptuu/conda-smithy\nINFO:conda_smithy.configure_feedstock:__pycache__ rendering is skipped\nINFO:conda_smithy.configure_feedstock:README rendering is skipped\nINFO:conda_smithy.configure_feedstock:pypy37-windows.yaml is closed now. Removing\nINFO:conda_smithy.configure_feedstock:python312.yaml from feedstock is ignored and upstream version is used\nINFO:conda_smithy.configure_feedstock:pypy37.yaml is closed now. Removing\nINFO:conda_smithy.configure_feedstock:python310.yaml is closed now. Removing\nWARNING: Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.\nWARNING: Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.\nWARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.23\nINFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmpgk3wptuu/conda-smithy/share/conda-forge/migrations/python312.yaml\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 758, in main\n    args.subcommand_func(args)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 601, in __call__\n    self._call(args, args.temporary_directory)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 604, in _call\n    configure_feedstock.main(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2770, in main\n    render_travis(env, config, forge_dir, return_metadata=True)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 1542, in render_travis\n    return _render_ci_provider(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 1051, in _render_ci_provider\n    raise RuntimeError(\nRuntimeError: Travis CI can only be used for 'linux_aarch64', 'linux_ppc64le' or 'linux_s390x' native builds, not 'osx_64', to avoid using open-source build minutes!\n\n'",
  "traceback": [
   "Traceback (most recent call last):",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 567, in _run_migrator_on_feedstock_branch",
   "    migrator_uid, pr_json = run(",
   "                            ^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 255, in run",
   "    rerender_msg = rerender_feedstock(feedstock_dir, timeout=900)",
   "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/rerender_feedstock.py\", line 49, in rerender_feedstock",
   "    return rerender_feedstock_containerized(",
   "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/rerender_feedstock.py\", line 102, in rerender_feedstock_containerized",
   "    data = run_container_task(",
   "           ^^^^^^^^^^^^^^^^^^^",
   "  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py\", line 286, in run_container_task",
   "    raise ContainerRuntimeError(",
   "conda_forge_tick.utils.ContainerRuntimeError: Error running rerender-feedstock in container - error RuntimeError raised:",
   "'Failed to rerender.",
   "output: Adding in variants from internal_defaults",
   "Adding in variants from /tmp/tmpgk3wptuu/conda-smithy/conda_build_config.yaml",
   "INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2024.08.18.18.50.57",
   "INFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmpgk3wptuu/conda-smithy",
   "INFO:conda_smithy.configure_feedstock:__pycache__ rendering is skipped",
   "INFO:conda_smithy.configure_feedstock:README rendering is skipped",
   "INFO:conda_smithy.configure_feedstock:pypy37-windows.yaml is closed now. Removing",
   "INFO:conda_smithy.configure_feedstock:python312.yaml from feedstock is ignored and upstream version is used",
   "INFO:conda_smithy.configure_feedstock:pypy37.yaml is closed now. Removing",
   "INFO:conda_smithy.configure_feedstock:python310.yaml is closed now. Removing",
   "WARNING: Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.",
   "WARNING: Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.",
   "WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.23",
   "INFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmpgk3wptuu/conda-smithy/share/conda-forge/migrations/python312.yaml",
   "Traceback (most recent call last):",
   "  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>",
   "    sys.exit(main())",
   "             ^^^^^^",
   "  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 758, in main",
   "    args.subcommand_func(args)",
   "  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 601, in __call__",
   "    self._call(args, args.temporary_directory)",
   "  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 604, in _call",
   "    configure_feedstock.main(",
   "  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2770, in main",
   "    render_travis(env, config, forge_dir, return_metadata=True)",
   "  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 1542, in render_travis",
   "    return _render_ci_provider(",
   "           ^^^^^^^^^^^^^^^^^^^^",
   "  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 1051, in _render_ci_provider",
   "    raise RuntimeError(",
   "RuntimeError: Travis CI can only be used for 'linux_aarch64', 'linux_ppc64le' or 'linux_s390x' native builds, not 'osx_64', to avoid using open-source build minutes!",
   "",
   "'",
   ""
  ]
 },
 "pinning_version": "2021.11.13.15.55.10",
 "pre_pr_migrator_attempts": {
  "pypy38": 846,
  "python311": 840,
  "python312": 723
 },
 "pre_pr_migrator_status": {
  "pypy38": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/10339014524\">bot CI job</a>): main:\nError running rerender-feedstock in container - error RuntimeError raised:\n'Failed to rerender.\noutput: Traceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 758, in main\n    args.subcommand_func(args)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 601, in __call__\n    self._call(args, args.temporary_directory)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 604, in _call\n    configure_feedstock.main(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2740, in main\n    exclusive_config_file, cf_pinning_ver = get_cached_cfp_file_path(\n                                            ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2553, in get_cached_cfp_file_path\n    current_pinning_version = get_most_recent_version(\n                              ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2426, in get_most_recent_version\n    request.raise_for_status()\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/models.py\", line 1024, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 524 Server Error:  for url: https://api.anaconda.org/package/conda-forge/conda-forge-pinning\n\n'",
  "python311": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/6282344026\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1257, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 290, in run\n    eval_cmd(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/os_utils.py\", line 36, in eval_cmd\n    c.check_returncode()\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.10/subprocess.py\", line 457, in check_returncode\n    raise CalledProcessError(self.returncode, self.args, self.stdout,\nsubprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.\n",
  "python312": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/10442343488\">bot CI job</a>): main:\nError running rerender-feedstock in container - error RuntimeError raised:\n'Failed to rerender.\noutput: Adding in variants from internal_defaults\nAdding in variants from /tmp/tmpgk3wptuu/conda-smithy/conda_build_config.yaml\nINFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2024.08.18.18.50.57\nINFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmpgk3wptuu/conda-smithy\nINFO:conda_smithy.configure_feedstock:__pycache__ rendering is skipped\nINFO:conda_smithy.configure_feedstock:README rendering is skipped\nINFO:conda_smithy.configure_feedstock:pypy37-windows.yaml is closed now. Removing\nINFO:conda_smithy.configure_feedstock:python312.yaml from feedstock is ignored and upstream version is used\nINFO:conda_smithy.configure_feedstock:pypy37.yaml is closed now. Removing\nINFO:conda_smithy.configure_feedstock:python310.yaml is closed now. Removing\nWARNING: Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.\nWARNING: Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.\nWARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.23\nINFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmpgk3wptuu/conda-smithy/share/conda-forge/migrations/python312.yaml\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/bin/conda-smithy\", line 10, in <module>\n    sys.exit(main())\n             ^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 758, in main\n    args.subcommand_func(args)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 601, in __call__\n    self._call(args, args.temporary_directory)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/cli.py\", line 604, in _call\n    configure_feedstock.main(\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 2770, in main\n    render_travis(env, config, forge_dir, return_metadata=True)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 1542, in render_travis\n    return _render_ci_provider(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py\", line 1051, in _render_ci_provider\n    raise RuntimeError(\nRuntimeError: Travis CI can only be used for 'linux_aarch64', 'linux_ppc64le' or 'linux_s390x' native builds, not 'osx_64', to avoid using open-source build minutes!\n\n'"
 },
 "smithy_version": "3.14.3"
}